initial development
ImpressionableRaccoon/GophKeeper pull request #1
Opened 2023-05-07 19:26 UTC by ImpressionableRaccoon

2023-05-14 09:17 UTC, kilchik requested changes
Понравилась структура проекта.
Лаконичная схема хранения, помню, обсуждали на 1-1. Тут даже реляционная база не нужна. Есть только один нюанс - мы предполагаем работу над заданием по ТЗ. При том, что проект действительно можно выполнить без регистрации и авторизации в явном виде, они все же требуются по ТЗ. С одной стороны - для того, чтобы потренироваться решать такую типовую задачу, с другой - потому что, если рассматривать проект как боевой, тебе так или иначе понадобится такое понятие как user. Ты захочешь банить пользователей, захочешь сделать для них тарифные планы, лимиты на хранение и т д. Давай оставим этот момент пока так, если время останется - очень хочется, чтобы пользователи добавились в проект. Хотя текущая схема не может не доставлять своей простотой.
По proto: еще нужен update, хотя предполагаю, что ты планировал его через delete и create сделать, но транзакционно выполнить так его не получится.
Нужно добавить подробное логирование в сервер, чтобы было возможно разбираться с проблемами на запущенном сервере.
Добавь еще пжлст Makefile с командами для сборки клиента/сервера, прогона тестов и линтеров

2023-05-14 09:17 UTC, kilchik commented on cmd/server/main.go
> +		panic(fmt.Errorf("error create server storage: %w", err))
Паникам лучше предпочесть logger.Fatal

2023-05-14 09:24 UTC, ImpressionableRaccoon commented on cmd/server/main.go
> +		panic(fmt.Errorf("error create server storage: %w", err))
Я там поменял на logger.Panic
Хочу, чтобы все defer выше отрабатывали нормально, а не просто делался sys.Exit()

2023-05-21 08:11 UTC, kilchik requested changes
Нужно добавить метод для редактирования секретов и тесты (покрытие кода тестами должно составлять 80%)

2023-05-21 08:11 UTC, kilchik commented on cmd/client/main.go
> +			logger.Panic("gen new key failed", zap.Error(err))
Паник на клиенте быть не должно, должны быть красивые ошибки для пользователя о том, что именно он сделал не так, и как ему это исправить

2023-05-21 08:11 UTC, kilchik commented on cmd/client/main.go
> +	config := zap.NewProductionConfig()
Логи с клиента стоит писать в файл, а не в консоль

2023-05-21 08:11 UTC, kilchik commented on internal/service/service.go
> +		return "", err
Ошибки по всем коду нужно обрабатывать, а не просто прокидывать наверх: либо снабдив префиксом, либо создав кастомную ошибку, пробросить выше

2023-05-24 18:58 UTC, ImpressionableRaccoon commented
покрытие ☺️
![image](https://github.com/ImpressionableRaccoon/GophKeeper/assets/47372390/8930a28f-5a0d-48b9-bfe3-8b9b490a684a)

2023-05-29 13:29 UTC, merged